main = ".open-next/worker.js"
name = "civic-dashboard-web"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
routes = [{ pattern = "civicdashboard.ca", custom_domain = true }]
preview_urls = true

[observability.logs]
enabled = true

[vars]
HOSTNAME_FOR_EMAIL_LINKS = "https://civicdashboard.ca"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "civic-dashboard-inc-cache"
preview_bucket_name = "civic-dashboard-inc-cache-preview"