main = ".open-next/worker.js"
name = "civic-dashboard-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
routes = [{ pattern = "civicdashboard.ca", custom_domain = true }]

[observability.logs]
enabled = true

[vars]
HOSTNAME_FOR_EMAIL_LINKS = "https://civicdashboard.ca"
