import { AgendaItem } from '@/database/queries/agendaItems';

/** Example agenda items used only for in-app email previews. */
export const SAMPLE_AGENDA_ITEMS: AgendaItem[] = [
  {
    id: 'sample-1',
    termId: 0,
    agendaItemId: -1,
    councilAgendaItemId: 0,
    decisionBodyId: 0,
    meetingId: 0,
    itemProcessId: 0,
    decisionBodyName: 'City Council',
    meetingDate: 0,
    reference: '2026.EX1.1',
    termYear: '2026',
    agendaCd: 'A',
    meetingNumber: '1',
    itemStatus: 'Scheduled',
    agendaItemTitle: 'Cycling Network Plan Update',
    agendaItemSummary:
      '<p>Report on proposed updates to the cycling network plan, including new protected bike lanes and intersection safety improvements.</p>',
    agendaItemRecommendation: null,
    decisionRecommendations: null,
    decisionAdvice: null,
    subjectTerms: '',
    wardId: null,
    backgroundAttachmentId: null,
    agendaItemAddress: null,
    address: null,
    geoLocation: null,
    planningApplicationNumber: null,
    neighbourhoodId: null,
  },
  {
    id: 'sample-2',
    termId: 0,
    agendaItemId: -2,
    councilAgendaItemId: 0,
    decisionBodyId: 0,
    meetingId: 0,
    itemProcessId: 0,
    decisionBodyName: 'Planning and Housing Committee',
    meetingDate: 0,
    reference: '2026.PH2.3',
    termYear: '2026',
    agendaCd: 'A',
    meetingNumber: '2',
    itemStatus: 'Scheduled',
    agendaItemTitle: 'Affordable Housing Near Transit',
    agendaItemSummary:
      '<p>Consideration of a proposal to increase affordable housing supply near major transit stations through zoning and funding recommendations.</p>',
    agendaItemRecommendation: null,
    decisionRecommendations: null,
    decisionAdvice: null,
    subjectTerms: '',
    wardId: null,
    backgroundAttachmentId: null,
    agendaItemAddress: null,
    address: null,
    geoLocation: null,
    planningApplicationNumber: null,
    neighbourhoodId: null,
  },
  {
    id: 'sample-3',
    termId: 0,
    agendaItemId: -3,
    councilAgendaItemId: 0,
    decisionBodyId: 0,
    meetingId: 0,
    itemProcessId: 0,
    decisionBodyName: 'Infrastructure and Environment Committee',
    meetingDate: 0,
    reference: '2026.IE3.5',
    termYear: '2026',
    agendaCd: 'A',
    meetingNumber: '3',
    itemStatus: 'Scheduled',
    agendaItemTitle: 'Park Renewal and Tree Canopy Expansion',
    agendaItemSummary:
      '<p>Request for funding to renew local parks and expand the urban tree canopy in underserved neighbourhoods.</p>',
    agendaItemRecommendation: null,
    decisionRecommendations: null,
    decisionAdvice: null,
    subjectTerms: '',
    wardId: null,
    backgroundAttachmentId: null,
    agendaItemAddress: null,
    address: null,
    geoLocation: null,
    planningApplicationNumber: null,
    neighbourhoodId: null,
  },
];
