import { RawAgendaItemConsiderations } from '@/database/allDbTypes';

export const agendaItemConflictColumns = [
  'address',
  'agendaCd',
  'agendaItemAddress',
  'agendaItemId',
  'agendaItemRecommendation',
  'agendaItemSummary',
  'agendaItemTitle',
  'backgroundAttachmentId',
  'councilAgendaItemId',
  'decisionAdvice',
  'decisionBodyId',
  'decisionBodyName',
  'decisionRecommendations',
  'geoLocation',
  'id',
  'itemProcessId',
  'itemStatus',
  'meetingDate',
  'meetingId',
  'meetingNumber',
  'neighbourhoodId',
  'planningApplicationNumber',
  'reference',
  'subjectTerms',
  'termId',
  'termYear',
  'wardId',
] as const satisfies (keyof RawAgendaItemConsiderations)[];
