/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export interface RawContacts {
  addressLine1: string | null;
  addressLine2: string | null;
  contactName: string;
  contactSlug: string;
  email: string;
  fax: string | null;
  inputRowNumber: Int8;
  locality: string | null;
  personalWebsite: string | null;
  phone: string | null;
  photoUrl: string | null;
  postalCode: string | null;
  primaryRole: string;
  province: string | null;
  term: string;
  wardId: string | null;
  wardName: string | null;
  wardSlug: string | null;
  website: string | null;
}

export interface RawVotes {
  agendaItemNumber: string;
  agendaItemTitle: string;
  committeeName: string;
  committeeSlug: string;
  contactName: string;
  contactSlug: string;
  dateTime: string;
  inputRowNumber: Int8;
  motionId: string;
  motionType: string;
  movedBy: string | null;
  result: string;
  secondedBy: string[] | null;
  term: string;
  vote: string;
  voteDescription: string;
}

export interface DB {
  RawContacts: RawContacts;
  RawVotes: RawVotes;
}
