name: Check migrations

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check migrations
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:54320/civic_dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start database
        run: docker compose up -d database

      - name: Run migrations
        run: npm run db:run-migrations

      - name: Check migration rollback
        run: npx kysely migrate:rollback --all

      - name: Run migrations again
        run: npm run db:run-migrations

      - name: Generate types
        run: npm run db:update-types

      - name: Check that there is no diff
        run: git diff --exit-code

      - name: Stop database
        if: always()
        run: docker compose down
